@startuml


class Mascota{
    + Dormir()
    + Comer()
    + Cagar()  
}
class Alimento
class Salud
class Ejercicio
class Pelota
class Felicidad
class Animal
class Emocion
class Habitacion
class Juego
class Moneda
class Juguete
class Tristeza
class Hambre
class Limite
class Espacio
class Vestimenta
class Casa 
class Ropa 
class Acsesorios


Mascota  --|> Animal
Mascota "1" o-- "*" Alimento
Alimento  --|>  Salud
Salud "*" --|> "*" Felicidad
Ejercicio "*" o-- "*" Salud
Felicidad  --|> Emocion
Mascota "1" o-- "5" Habitacion
Juego "1" *-- "1" Mascota
Juego "1" *-- "*" Moneda
Mascota "1" o-- "*" Moneda
Habitacion "1" *-- "*" Juguete
Mascota "1" *-- "1" Juguete
Pelota  --|>  Juguete
Tristeza  --|>  Emocion
Mascota "1" o-- "*" Ejercicio
Hambre  --|>  Tristeza
Mascota "1" o-- "1" Pelota
Juego "1" *-- "4" Limite
Limite  --|>  Espacio
Juego "1" *-- "1" Casa
Mascota "1" o-- "1" Casa
Mascota "1" o-- "*" Vestimenta
Vestimenta --|> Ropa
Vestimenta --|> Acsesorios




@enduml
